### ISSUE TITLE
Svg support and question about special characters

### ISSUE THREAD

**Issue by erf** [hlorenzi/font-inspect#1]
Hi, do you have any plans to support outputting SVG?

I looked at [google-font-to-svg-path](https://github.com/danmarshall/google-font-to-svg-path) which converts fonts to svg paths. However they use [opentype.js](https://github.com/opentypejs/opentype.js) which seem to lack support for special unicode characters, like  the following [issue](https://github.com/opentypejs/opentype.js/issues/446). Not sure if you support these? 

Thanks for your time.

**Comment by hlorenzi** [comment]
Unfortunately it doesn't support these kinds of character combinations... It just reads off the Unicode table embedded in the font data, which only accounts for simple mappings of `single Unicode codepoint -> glyph`. You can, however, extract a glyph by its internal index (unrelated to the assigned Unicode codepoint) which you can find by using the [web app](https://hlorenzi.github.io/font-js/).

But then again, it doesn't support exporting to SVG natively as of now. You could implement your own by using some code like [the one seen in the README file](https://github.com/hlorenzi/font-js#package-example), but using `font.getGlyphGeometry(glyphIndex)` without the simplification argument, to get the original bézier curves.

**Comment by erf** [comment]
Ok, thanks!

**Comment by evnb** [comment]
Does this support emoji and/or color/ bitmap fonts?

**Comment by hlorenzi** [comment]
No, it only currently supports old-fashioned glyph data (from the `glyf` table).
